### ISSUE TITLE
A question about the bitrate ladder

### ISSUE THREAD

**Issue by godka** [twitchtv/acm-mmsys-2020-grand-challenge#1]
https://github.com/twitchtv/acm-mmsys-2020-grand-challenge/blob/56e823d818bf0702af13d13c6d9f8896c83bebdc/dash-ll-server/gen_live_ingest.sh#L36

https://github.com/twitchtv/acm-mmsys-2020-grand-challenge/blob/56e823d818bf0702af13d13c6d9f8896c83bebdc/dash-ll-server/gen_live_ingest.sh#L37

As shown, does it mean that the video is encoded with **the same bitrates** but **different resolutions**?

Thx.

**Comment by johnBartos** [comment]
Hi @godka, sorry I missed this issue. They should be different bitrates, I'll update this now. Thanks!

**Comment by johnBartos** [comment]
Fixed, thanks again
