### ISSUE TITLE
Using latest version of dash.js

### ISSUE THREAD

**Issue by kefanchen** [twitchtv/acm-mmsys-2020-grand-challenge#10]
Hi, @johnBartos , thank you for setting up an environment to study the low latency streaming.

Can I just replace the dash.js directory in this repo with the latest version to test the new functions of low latency dash? As you know, dash v3.2 has adoptted some great solutions of this challenge, and we want to test them with certain networks. You mentioned that the dash.js in this repo is modified, so I wound like to know is it okay to simply replace the dash.js directory, or some coordination is needed to incorporate the latest dash.js with the rest of this repo?

Thank you for your attention.

**Comment by johnBartos** [comment]
Hey @kefanchen, you can replace it but you'll need to modify Dash.js to pre-request the segment before it's available. You might be able to skip this but I'm not sure what the impact will be. To be honest I can't remember where I made that change, but I don't remember it being too difficult.

**Comment by kefanchen** [comment]
> Hey @kefanchen, you can replace it but you'll need to modify Dash.js to pre-request the segment before it's available. You might be able to skip this but I'm not sure what the impact will be. To be honest I can't remember where I made that change, but I don't remember it being too difficult.

Thank you, I will try with your suggestion.

**Comment by kefanchen** [comment]
Thank you, it works.

**Comment by kefanchen** [comment]
Thank you, it works.
