### ISSUE TITLE
Perform a test run failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by nvduc** [twitchtv/acm-mmsys-2020-grand-challenge#2]
I got the following error when performing a test with 'node run.js' command on Ubuntu 16.04, 64bit.
$ node run.js
Error: Failed to launch the browser process! spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT

It seems the path for Chrome is not correctly configured.
Please give me any suggestions to correct this error.
Thanks,
Nguyen

**Comment by godka** [comment]
Please change the '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' to your-path-to-your-Chrome-application.

**Comment by johnBartos** [comment]
@godka That's correct, much appreciated! Will add to the readme.

**Comment by johnBartos** [comment]
Added
